# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paysfer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paysfer

 pod 'SDWebImage', '~> 4.0'
 pod 'Alamofire','~> 4.9.1'
 pod 'SDLoader'
 pod 'DropDown'
 pod 'CountryPickerView'
 pod 'IQKeyboardManagerSwift'
 pod 'GooglePlaces'
 pod 'GoogleMaps'
 pod 'SkyFloatingLabelTextField'
 pod 'SVProgressHUD'
# pod 'SCLAlertView'
 pod 'ProgressHUD'
 pod 'SideMenu'
 pod 'PKHUD', '~> 5.0'
 pod 'SCLAlertView'
 pod 'Cosmos'

 pod 'Firebase/Auth'
 pod 'GoogleSignIn'
 pod 'FirebaseUI/Facebook'



end
